# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='params.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cparams.proto\"U\n\rWishartParams\x12\n\n\x02nu\x18\x01 \x01(\x01\x12\x10\n\x08identity\x18\x02 \x01(\x08\x12\x0f\n\x05sigma\x18\x03 \x01(\x01H\x00\x12\x0b\n\x03\x64im\x18\x04 \x01(\x05\x42\x08\n\x06sigma_\"2\n\x14\x46ixedMultiPrecParams\x12\r\n\x05sigma\x18\x01 \x01(\x01\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\"$\n\x13\x46ixedUnivPrecParams\x12\r\n\x05sigma\x18\x01 \x01(\x01\"*\n\x0bGammaParams\x12\r\n\x05\x61lpha\x18\x01 \x01(\x01\x12\x0c\n\x04\x62\x65ta\x18\x02 \x01(\x01\"\x86\x02\n\rStraussParams\x12$\n\x05prior\x18\x01 \x01(\x0b\x32\x15.StraussParams.Priors\x12\"\n\x04init\x18\x02 \x01(\x0b\x32\x14.StraussParams.Inits\x12\x14\n\x0c\x66ixed_params\x18\x03 \x01(\x08\x1a\x64\n\x06Priors\x12\x0e\n\x06\x62\x65ta_l\x18\x01 \x01(\x01\x12\x0e\n\x06\x62\x65ta_u\x18\x02 \x01(\x01\x12\x0f\n\x07gamma_l\x18\x03 \x01(\x01\x12\x0f\n\x07gamma_u\x18\x04 \x01(\x01\x12\x0b\n\x03r_l\x18\x05 \x01(\x01\x12\x0b\n\x03r_u\x18\x06 \x01(\x01\x1a/\n\x05Inits\x12\x0c\n\x04\x62\x65ta\x18\x01 \x01(\x01\x12\r\n\x05gamma\x18\x02 \x01(\x01\x12\t\n\x01R\x18\x03 \x01(\x01\"\"\n\nNrepParams\x12\t\n\x01u\x18\x01 \x01(\x01\x12\t\n\x01p\x18\x02 \x01(\x01\":\n\tDPPParams\x12\n\n\x02nu\x18\x01 \x01(\x01\x12\x0b\n\x03rho\x18\x02 \x01(\x01\x12\t\n\x01N\x18\x03 \x01(\x05\x12\t\n\x01s\x18\x04 \x01(\x01\"\xe3\x02\n\x06Params\x12!\n\x07strauss\x18\x01 \x01(\x0b\x32\x0e.StraussParamsH\x00\x12\x1b\n\x04nrep\x18\x02 \x01(\x0b\x32\x0b.NrepParamsH\x00\x12\x19\n\x03\x64pp\x18\x03 \x01(\x0b\x32\n.DPPParamsH\x00\x12\x31\n\x10\x66ixed_multi_prec\x18\x04 \x01(\x0b\x32\x15.FixedMultiPrecParamsH\x01\x12!\n\x07wishart\x18\x05 \x01(\x0b\x32\x0e.WishartParamsH\x01\x12/\n\x0f\x66ixed_univ_prec\x18\x06 \x01(\x0b\x32\x14.FixedUnivPrecParamsH\x01\x12\"\n\ngamma_prec\x18\x07 \x01(\x0b\x32\x0c.GammaParamsH\x01\x12 \n\ngamma_jump\x18\x08 \x01(\x0b\x32\x0c.GammaParams\x12\x15\n\rmala_stepsize\x18\t \x01(\x01\x42\x0b\n\tpp_paramsB\r\n\x0bprec_paramsb\x06proto3'
)




_WISHARTPARAMS = _descriptor.Descriptor(
  name='WishartParams',
  full_name='WishartParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nu', full_name='WishartParams.nu', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identity', full_name='WishartParams.identity', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sigma', full_name='WishartParams.sigma', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='WishartParams.dim', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sigma_', full_name='WishartParams.sigma_',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=16,
  serialized_end=101,
)


_FIXEDMULTIPRECPARAMS = _descriptor.Descriptor(
  name='FixedMultiPrecParams',
  full_name='FixedMultiPrecParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sigma', full_name='FixedMultiPrecParams.sigma', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='FixedMultiPrecParams.dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=153,
)


_FIXEDUNIVPRECPARAMS = _descriptor.Descriptor(
  name='FixedUnivPrecParams',
  full_name='FixedUnivPrecParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sigma', full_name='FixedUnivPrecParams.sigma', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=191,
)


_GAMMAPARAMS = _descriptor.Descriptor(
  name='GammaParams',
  full_name='GammaParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha', full_name='GammaParams.alpha', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beta', full_name='GammaParams.beta', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=235,
)


_STRAUSSPARAMS_PRIORS = _descriptor.Descriptor(
  name='Priors',
  full_name='StraussParams.Priors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='beta_l', full_name='StraussParams.Priors.beta_l', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beta_u', full_name='StraussParams.Priors.beta_u', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma_l', full_name='StraussParams.Priors.gamma_l', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma_u', full_name='StraussParams.Priors.gamma_u', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_l', full_name='StraussParams.Priors.r_l', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r_u', full_name='StraussParams.Priors.r_u', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=451,
)

_STRAUSSPARAMS_INITS = _descriptor.Descriptor(
  name='Inits',
  full_name='StraussParams.Inits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='beta', full_name='StraussParams.Inits.beta', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='StraussParams.Inits.gamma', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='R', full_name='StraussParams.Inits.R', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=500,
)

_STRAUSSPARAMS = _descriptor.Descriptor(
  name='StraussParams',
  full_name='StraussParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prior', full_name='StraussParams.prior', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='init', full_name='StraussParams.init', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fixed_params', full_name='StraussParams.fixed_params', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STRAUSSPARAMS_PRIORS, _STRAUSSPARAMS_INITS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=500,
)


_NREPPARAMS = _descriptor.Descriptor(
  name='NrepParams',
  full_name='NrepParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='u', full_name='NrepParams.u', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='NrepParams.p', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=536,
)


_DPPPARAMS = _descriptor.Descriptor(
  name='DPPParams',
  full_name='DPPParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nu', full_name='DPPParams.nu', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rho', full_name='DPPParams.rho', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='N', full_name='DPPParams.N', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s', full_name='DPPParams.s', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=596,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strauss', full_name='Params.strauss', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nrep', full_name='Params.nrep', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dpp', full_name='Params.dpp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fixed_multi_prec', full_name='Params.fixed_multi_prec', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wishart', full_name='Params.wishart', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fixed_univ_prec', full_name='Params.fixed_univ_prec', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma_prec', full_name='Params.gamma_prec', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma_jump', full_name='Params.gamma_jump', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mala_stepsize', full_name='Params.mala_stepsize', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='pp_params', full_name='Params.pp_params',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='prec_params', full_name='Params.prec_params',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=599,
  serialized_end=954,
)

_WISHARTPARAMS.oneofs_by_name['sigma_'].fields.append(
  _WISHARTPARAMS.fields_by_name['sigma'])
_WISHARTPARAMS.fields_by_name['sigma'].containing_oneof = _WISHARTPARAMS.oneofs_by_name['sigma_']
_STRAUSSPARAMS_PRIORS.containing_type = _STRAUSSPARAMS
_STRAUSSPARAMS_INITS.containing_type = _STRAUSSPARAMS
_STRAUSSPARAMS.fields_by_name['prior'].message_type = _STRAUSSPARAMS_PRIORS
_STRAUSSPARAMS.fields_by_name['init'].message_type = _STRAUSSPARAMS_INITS
_PARAMS.fields_by_name['strauss'].message_type = _STRAUSSPARAMS
_PARAMS.fields_by_name['nrep'].message_type = _NREPPARAMS
_PARAMS.fields_by_name['dpp'].message_type = _DPPPARAMS
_PARAMS.fields_by_name['fixed_multi_prec'].message_type = _FIXEDMULTIPRECPARAMS
_PARAMS.fields_by_name['wishart'].message_type = _WISHARTPARAMS
_PARAMS.fields_by_name['fixed_univ_prec'].message_type = _FIXEDUNIVPRECPARAMS
_PARAMS.fields_by_name['gamma_prec'].message_type = _GAMMAPARAMS
_PARAMS.fields_by_name['gamma_jump'].message_type = _GAMMAPARAMS
_PARAMS.oneofs_by_name['pp_params'].fields.append(
  _PARAMS.fields_by_name['strauss'])
_PARAMS.fields_by_name['strauss'].containing_oneof = _PARAMS.oneofs_by_name['pp_params']
_PARAMS.oneofs_by_name['pp_params'].fields.append(
  _PARAMS.fields_by_name['nrep'])
_PARAMS.fields_by_name['nrep'].containing_oneof = _PARAMS.oneofs_by_name['pp_params']
_PARAMS.oneofs_by_name['pp_params'].fields.append(
  _PARAMS.fields_by_name['dpp'])
_PARAMS.fields_by_name['dpp'].containing_oneof = _PARAMS.oneofs_by_name['pp_params']
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['fixed_multi_prec'])
_PARAMS.fields_by_name['fixed_multi_prec'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['wishart'])
_PARAMS.fields_by_name['wishart'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['fixed_univ_prec'])
_PARAMS.fields_by_name['fixed_univ_prec'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['gamma_prec'])
_PARAMS.fields_by_name['gamma_prec'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
DESCRIPTOR.message_types_by_name['WishartParams'] = _WISHARTPARAMS
DESCRIPTOR.message_types_by_name['FixedMultiPrecParams'] = _FIXEDMULTIPRECPARAMS
DESCRIPTOR.message_types_by_name['FixedUnivPrecParams'] = _FIXEDUNIVPRECPARAMS
DESCRIPTOR.message_types_by_name['GammaParams'] = _GAMMAPARAMS
DESCRIPTOR.message_types_by_name['StraussParams'] = _STRAUSSPARAMS
DESCRIPTOR.message_types_by_name['NrepParams'] = _NREPPARAMS
DESCRIPTOR.message_types_by_name['DPPParams'] = _DPPPARAMS
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WishartParams = _reflection.GeneratedProtocolMessageType('WishartParams', (_message.Message,), {
  'DESCRIPTOR' : _WISHARTPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:WishartParams)
  })
_sym_db.RegisterMessage(WishartParams)

FixedMultiPrecParams = _reflection.GeneratedProtocolMessageType('FixedMultiPrecParams', (_message.Message,), {
  'DESCRIPTOR' : _FIXEDMULTIPRECPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:FixedMultiPrecParams)
  })
_sym_db.RegisterMessage(FixedMultiPrecParams)

FixedUnivPrecParams = _reflection.GeneratedProtocolMessageType('FixedUnivPrecParams', (_message.Message,), {
  'DESCRIPTOR' : _FIXEDUNIVPRECPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:FixedUnivPrecParams)
  })
_sym_db.RegisterMessage(FixedUnivPrecParams)

GammaParams = _reflection.GeneratedProtocolMessageType('GammaParams', (_message.Message,), {
  'DESCRIPTOR' : _GAMMAPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:GammaParams)
  })
_sym_db.RegisterMessage(GammaParams)

StraussParams = _reflection.GeneratedProtocolMessageType('StraussParams', (_message.Message,), {

  'Priors' : _reflection.GeneratedProtocolMessageType('Priors', (_message.Message,), {
    'DESCRIPTOR' : _STRAUSSPARAMS_PRIORS,
    '__module__' : 'params_pb2'
    # @@protoc_insertion_point(class_scope:StraussParams.Priors)
    })
  ,

  'Inits' : _reflection.GeneratedProtocolMessageType('Inits', (_message.Message,), {
    'DESCRIPTOR' : _STRAUSSPARAMS_INITS,
    '__module__' : 'params_pb2'
    # @@protoc_insertion_point(class_scope:StraussParams.Inits)
    })
  ,
  'DESCRIPTOR' : _STRAUSSPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:StraussParams)
  })
_sym_db.RegisterMessage(StraussParams)
_sym_db.RegisterMessage(StraussParams.Priors)
_sym_db.RegisterMessage(StraussParams.Inits)

NrepParams = _reflection.GeneratedProtocolMessageType('NrepParams', (_message.Message,), {
  'DESCRIPTOR' : _NREPPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:NrepParams)
  })
_sym_db.RegisterMessage(NrepParams)

DPPParams = _reflection.GeneratedProtocolMessageType('DPPParams', (_message.Message,), {
  'DESCRIPTOR' : _DPPPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:DPPParams)
  })
_sym_db.RegisterMessage(DPPParams)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:Params)
  })
_sym_db.RegisterMessage(Params)


# @@protoc_insertion_point(module_scope)
