# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: params.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='params.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cparams.proto\"U\n\rWishartParams\x12\n\n\x02nu\x18\x01 \x01(\x01\x12\x10\n\x08identity\x18\x02 \x01(\x08\x12\x0f\n\x05sigma\x18\x03 \x01(\x01H\x00\x12\x0b\n\x03\x64im\x18\x04 \x01(\x05\x42\x08\n\x06sigma_\"2\n\x14\x46ixedMultiPrecParams\x12\r\n\x05sigma\x18\x01 \x01(\x01\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\"$\n\x13\x46ixedUnivPrecParams\x12\r\n\x05sigma\x18\x01 \x01(\x01\"*\n\x0bGammaParams\x12\r\n\x05\x61lpha\x18\x01 \x01(\x01\x12\x0c\n\x04\x62\x65ta\x18\x02 \x01(\x01\",\n\tDPPParams\x12\t\n\x01\x63\x18\x01 \x01(\x01\x12\t\n\x01n\x18\x02 \x01(\x05\x12\t\n\x01s\x18\x03 \x01(\x01\"\xcd\x02\n\x06Params\x12\x17\n\x03\x64pp\x18\x01 \x01(\x0b\x32\n.DPPParams\x12\x31\n\x10\x66ixed_multi_prec\x18\x02 \x01(\x0b\x32\x15.FixedMultiPrecParamsH\x00\x12!\n\x07wishart\x18\x03 \x01(\x0b\x32\x0e.WishartParamsH\x00\x12/\n\x0f\x66ixed_univ_prec\x18\x04 \x01(\x0b\x32\x14.FixedUnivPrecParamsH\x00\x12\"\n\ngamma_prec\x18\x05 \x01(\x0b\x32\x0c.GammaParamsH\x00\x12\x0c\n\x04\x64imf\x18\x06 \x01(\x05\x12\t\n\x01\x61\x18\x07 \x01(\x01\x12\x11\n\talphajump\x18\x08 \x01(\x01\x12\x10\n\x08\x62\x65tajump\x18\t \x01(\x01\x12\x0e\n\x06\x61gamma\x18\n \x01(\x01\x12\x0e\n\x06\x62gamma\x18\x0b \x01(\x01\x12\x12\n\nprop_sigma\x18\x0c \x01(\x01\x42\r\n\x0bprec_paramsb\x06proto3'
)




_WISHARTPARAMS = _descriptor.Descriptor(
  name='WishartParams',
  full_name='WishartParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nu', full_name='WishartParams.nu', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identity', full_name='WishartParams.identity', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sigma', full_name='WishartParams.sigma', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='WishartParams.dim', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sigma_', full_name='WishartParams.sigma_',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=16,
  serialized_end=101,
)


_FIXEDMULTIPRECPARAMS = _descriptor.Descriptor(
  name='FixedMultiPrecParams',
  full_name='FixedMultiPrecParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sigma', full_name='FixedMultiPrecParams.sigma', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dim', full_name='FixedMultiPrecParams.dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=153,
)


_FIXEDUNIVPRECPARAMS = _descriptor.Descriptor(
  name='FixedUnivPrecParams',
  full_name='FixedUnivPrecParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sigma', full_name='FixedUnivPrecParams.sigma', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=191,
)


_GAMMAPARAMS = _descriptor.Descriptor(
  name='GammaParams',
  full_name='GammaParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha', full_name='GammaParams.alpha', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beta', full_name='GammaParams.beta', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=235,
)


_DPPPARAMS = _descriptor.Descriptor(
  name='DPPParams',
  full_name='DPPParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='c', full_name='DPPParams.c', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='DPPParams.n', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s', full_name='DPPParams.s', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=281,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dpp', full_name='Params.dpp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fixed_multi_prec', full_name='Params.fixed_multi_prec', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wishart', full_name='Params.wishart', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fixed_univ_prec', full_name='Params.fixed_univ_prec', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma_prec', full_name='Params.gamma_prec', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dimf', full_name='Params.dimf', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='a', full_name='Params.a', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alphajump', full_name='Params.alphajump', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='betajump', full_name='Params.betajump', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agamma', full_name='Params.agamma', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bgamma', full_name='Params.bgamma', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prop_sigma', full_name='Params.prop_sigma', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='prec_params', full_name='Params.prec_params',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=284,
  serialized_end=617,
)

_WISHARTPARAMS.oneofs_by_name['sigma_'].fields.append(
  _WISHARTPARAMS.fields_by_name['sigma'])
_WISHARTPARAMS.fields_by_name['sigma'].containing_oneof = _WISHARTPARAMS.oneofs_by_name['sigma_']
_PARAMS.fields_by_name['dpp'].message_type = _DPPPARAMS
_PARAMS.fields_by_name['fixed_multi_prec'].message_type = _FIXEDMULTIPRECPARAMS
_PARAMS.fields_by_name['wishart'].message_type = _WISHARTPARAMS
_PARAMS.fields_by_name['fixed_univ_prec'].message_type = _FIXEDUNIVPRECPARAMS
_PARAMS.fields_by_name['gamma_prec'].message_type = _GAMMAPARAMS
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['fixed_multi_prec'])
_PARAMS.fields_by_name['fixed_multi_prec'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['wishart'])
_PARAMS.fields_by_name['wishart'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['fixed_univ_prec'])
_PARAMS.fields_by_name['fixed_univ_prec'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
_PARAMS.oneofs_by_name['prec_params'].fields.append(
  _PARAMS.fields_by_name['gamma_prec'])
_PARAMS.fields_by_name['gamma_prec'].containing_oneof = _PARAMS.oneofs_by_name['prec_params']
DESCRIPTOR.message_types_by_name['WishartParams'] = _WISHARTPARAMS
DESCRIPTOR.message_types_by_name['FixedMultiPrecParams'] = _FIXEDMULTIPRECPARAMS
DESCRIPTOR.message_types_by_name['FixedUnivPrecParams'] = _FIXEDUNIVPRECPARAMS
DESCRIPTOR.message_types_by_name['GammaParams'] = _GAMMAPARAMS
DESCRIPTOR.message_types_by_name['DPPParams'] = _DPPPARAMS
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WishartParams = _reflection.GeneratedProtocolMessageType('WishartParams', (_message.Message,), {
  'DESCRIPTOR' : _WISHARTPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:WishartParams)
  })
_sym_db.RegisterMessage(WishartParams)

FixedMultiPrecParams = _reflection.GeneratedProtocolMessageType('FixedMultiPrecParams', (_message.Message,), {
  'DESCRIPTOR' : _FIXEDMULTIPRECPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:FixedMultiPrecParams)
  })
_sym_db.RegisterMessage(FixedMultiPrecParams)

FixedUnivPrecParams = _reflection.GeneratedProtocolMessageType('FixedUnivPrecParams', (_message.Message,), {
  'DESCRIPTOR' : _FIXEDUNIVPRECPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:FixedUnivPrecParams)
  })
_sym_db.RegisterMessage(FixedUnivPrecParams)

GammaParams = _reflection.GeneratedProtocolMessageType('GammaParams', (_message.Message,), {
  'DESCRIPTOR' : _GAMMAPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:GammaParams)
  })
_sym_db.RegisterMessage(GammaParams)

DPPParams = _reflection.GeneratedProtocolMessageType('DPPParams', (_message.Message,), {
  'DESCRIPTOR' : _DPPPARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:DPPParams)
  })
_sym_db.RegisterMessage(DPPParams)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'params_pb2'
  # @@protoc_insertion_point(class_scope:Params)
  })
_sym_db.RegisterMessage(Params)


# @@protoc_insertion_point(module_scope)
