// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

#include "state.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_state_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EigenMatrix_state_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_state_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EigenVector_state_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_state_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_LambdaBlock_state_2eproto;
class EigenMatrixDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EigenMatrix> _instance;
} _EigenMatrix_default_instance_;
class EigenVectorDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<EigenVector> _instance;
} _EigenVector_default_instance_;
class LambdaBlockDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LambdaBlock> _instance;
} _LambdaBlock_default_instance_;
class MultivariateMixtureStateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MultivariateMixtureState> _instance;
} _MultivariateMixtureState_default_instance_;
class UnivariateMixtureStateDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<UnivariateMixtureState> _instance;
} _UnivariateMixtureState_default_instance_;
static void InitDefaultsscc_info_EigenMatrix_state_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_EigenMatrix_default_instance_;
    new (ptr) ::EigenMatrix();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EigenMatrix_state_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_EigenMatrix_state_2eproto}, {}};

static void InitDefaultsscc_info_EigenVector_state_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_EigenVector_default_instance_;
    new (ptr) ::EigenVector();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_EigenVector_state_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_EigenVector_state_2eproto}, {}};

static void InitDefaultsscc_info_LambdaBlock_state_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_LambdaBlock_default_instance_;
    new (ptr) ::LambdaBlock();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_LambdaBlock_state_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_LambdaBlock_state_2eproto}, {
      &scc_info_EigenMatrix_state_2eproto.base,}};

static void InitDefaultsscc_info_MultivariateMixtureState_state_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_MultivariateMixtureState_default_instance_;
    new (ptr) ::MultivariateMixtureState();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_MultivariateMixtureState_state_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_MultivariateMixtureState_state_2eproto}, {
      &scc_info_EigenVector_state_2eproto.base,
      &scc_info_EigenMatrix_state_2eproto.base,
      &scc_info_LambdaBlock_state_2eproto.base,}};

static void InitDefaultsscc_info_UnivariateMixtureState_state_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_UnivariateMixtureState_default_instance_;
    new (ptr) ::UnivariateMixtureState();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_UnivariateMixtureState_state_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_UnivariateMixtureState_state_2eproto}, {
      &scc_info_EigenVector_state_2eproto.base,
      &scc_info_LambdaBlock_state_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_state_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_state_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_state_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_state_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::EigenMatrix, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::EigenMatrix, rows_),
  PROTOBUF_FIELD_OFFSET(::EigenMatrix, cols_),
  PROTOBUF_FIELD_OFFSET(::EigenMatrix, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::EigenVector, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::EigenVector, size_),
  PROTOBUF_FIELD_OFFSET(::EigenVector, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::LambdaBlock, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::LambdaBlock, tau_),
  PROTOBUF_FIELD_OFFSET(::LambdaBlock, phi_),
  PROTOBUF_FIELD_OFFSET(::LambdaBlock, psi_),
  PROTOBUF_FIELD_OFFSET(::LambdaBlock, lambda_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, ma_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, mna_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, mtot_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, a_means_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, na_means_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, a_deltas_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, na_deltas_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, a_jumps_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, na_jumps_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, clus_alloc_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, u_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, etas_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, sigma_bar_),
  PROTOBUF_FIELD_OFFSET(::MultivariateMixtureState, lamb_block_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, ma_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, mna_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, mtot_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, a_means_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, na_means_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, a_deltas_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, na_deltas_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, a_jumps_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, na_jumps_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, clus_alloc_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, u_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, etas_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, sigma_bar_),
  PROTOBUF_FIELD_OFFSET(::UnivariateMixtureState, lamb_block_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::EigenMatrix)},
  { 8, -1, sizeof(::EigenVector)},
  { 15, -1, sizeof(::LambdaBlock)},
  { 24, -1, sizeof(::MultivariateMixtureState)},
  { 43, -1, sizeof(::UnivariateMixtureState)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_EigenMatrix_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_EigenVector_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_LambdaBlock_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_MultivariateMixtureState_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_UnivariateMixtureState_default_instance_),
};

const char descriptor_table_protodef_state_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013state.proto\"7\n\013EigenMatrix\022\014\n\004rows\030\001 \001"
  "(\r\022\014\n\004cols\030\002 \001(\r\022\014\n\004data\030\003 \003(\001\")\n\013EigenV"
  "ector\022\014\n\004size\030\001 \001(\r\022\014\n\004data\030\002 \003(\001\"n\n\013Lam"
  "bdaBlock\022\013\n\003tau\030\001 \001(\001\022\031\n\003phi\030\002 \001(\0132\014.Eig"
  "enMatrix\022\031\n\003psi\030\003 \001(\0132\014.EigenMatrix\022\034\n\006l"
  "ambda\030\004 \001(\0132\014.EigenMatrix\"\376\002\n\030Multivaria"
  "teMixtureState\022\n\n\002ma\030\001 \001(\005\022\013\n\003mna\030\002 \001(\005\022"
  "\014\n\004mtot\030\003 \001(\005\022\035\n\007a_means\030\004 \003(\0132\014.EigenVe"
  "ctor\022\036\n\010na_means\030\005 \003(\0132\014.EigenVector\022\036\n\010"
  "a_deltas\030\006 \003(\0132\014.EigenMatrix\022\037\n\tna_delta"
  "s\030\007 \003(\0132\014.EigenMatrix\022\035\n\007a_jumps\030\010 \001(\0132\014"
  ".EigenVector\022\036\n\010na_jumps\030\t \001(\0132\014.EigenVe"
  "ctor\022\022\n\nclus_alloc\030\n \003(\005\022\t\n\001u\030\013 \001(\001\022\032\n\004e"
  "tas\030\014 \003(\0132\014.EigenVector\022\037\n\tsigma_bar\030\r \001"
  "(\0132\014.EigenVector\022 \n\nlamb_block\030\016 \001(\0132\014.L"
  "ambdaBlock\"\374\002\n\026UnivariateMixtureState\022\n\n"
  "\002ma\030\001 \001(\005\022\013\n\003mna\030\002 \001(\005\022\014\n\004mtot\030\003 \001(\005\022\035\n\007"
  "a_means\030\004 \001(\0132\014.EigenVector\022\036\n\010na_means\030"
  "\005 \001(\0132\014.EigenVector\022\036\n\010a_deltas\030\006 \001(\0132\014."
  "EigenVector\022\037\n\tna_deltas\030\007 \001(\0132\014.EigenVe"
  "ctor\022\035\n\007a_jumps\030\010 \001(\0132\014.EigenVector\022\036\n\010n"
  "a_jumps\030\t \001(\0132\014.EigenVector\022\022\n\nclus_allo"
  "c\030\n \003(\005\022\t\n\001u\030\013 \001(\001\022\032\n\004etas\030\014 \001(\0132\014.Eigen"
  "Vector\022\037\n\tsigma_bar\030\r \001(\0132\014.EigenVector\022"
  " \n\nlamb_block\030\016 \001(\0132\014.LambdaBlockb\006proto"
  "3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_state_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_state_2eproto_sccs[5] = {
  &scc_info_EigenMatrix_state_2eproto.base,
  &scc_info_EigenVector_state_2eproto.base,
  &scc_info_LambdaBlock_state_2eproto.base,
  &scc_info_MultivariateMixtureState_state_2eproto.base,
  &scc_info_UnivariateMixtureState_state_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_state_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_state_2eproto = {
  false, false, descriptor_table_protodef_state_2eproto, "state.proto", 1001,
  &descriptor_table_state_2eproto_once, descriptor_table_state_2eproto_sccs, descriptor_table_state_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_state_2eproto::offsets,
  file_level_metadata_state_2eproto, 5, file_level_enum_descriptors_state_2eproto, file_level_service_descriptors_state_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_state_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_state_2eproto)), true);

// ===================================================================

class EigenMatrix::_Internal {
 public:
};

EigenMatrix::EigenMatrix(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  data_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:EigenMatrix)
}
EigenMatrix::EigenMatrix(const EigenMatrix& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_(from.data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&rows_, &from.rows_,
    static_cast<size_t>(reinterpret_cast<char*>(&cols_) -
    reinterpret_cast<char*>(&rows_)) + sizeof(cols_));
  // @@protoc_insertion_point(copy_constructor:EigenMatrix)
}

void EigenMatrix::SharedCtor() {
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&rows_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&cols_) -
      reinterpret_cast<char*>(&rows_)) + sizeof(cols_));
}

EigenMatrix::~EigenMatrix() {
  // @@protoc_insertion_point(destructor:EigenMatrix)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void EigenMatrix::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void EigenMatrix::ArenaDtor(void* object) {
  EigenMatrix* _this = reinterpret_cast< EigenMatrix* >(object);
  (void)_this;
}
void EigenMatrix::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EigenMatrix::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EigenMatrix& EigenMatrix::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EigenMatrix_state_2eproto.base);
  return *internal_default_instance();
}


void EigenMatrix::Clear() {
// @@protoc_insertion_point(message_clear_start:EigenMatrix)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  ::memset(&rows_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cols_) -
      reinterpret_cast<char*>(&rows_)) + sizeof(cols_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EigenMatrix::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 rows = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          rows_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 cols = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          cols_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EigenMatrix::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:EigenMatrix)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 rows = 1;
  if (this->rows() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_rows(), target);
  }

  // uint32 cols = 2;
  if (this->cols() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_cols(), target);
  }

  // repeated double data = 3;
  if (this->_internal_data_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EigenMatrix)
  return target;
}

size_t EigenMatrix::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EigenMatrix)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double data = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // uint32 rows = 1;
  if (this->rows() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_rows());
  }

  // uint32 cols = 2;
  if (this->cols() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cols());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EigenMatrix::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EigenMatrix)
  GOOGLE_DCHECK_NE(&from, this);
  const EigenMatrix* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EigenMatrix>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EigenMatrix)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EigenMatrix)
    MergeFrom(*source);
  }
}

void EigenMatrix::MergeFrom(const EigenMatrix& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EigenMatrix)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (from.rows() != 0) {
    _internal_set_rows(from._internal_rows());
  }
  if (from.cols() != 0) {
    _internal_set_cols(from._internal_cols());
  }
}

void EigenMatrix::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EigenMatrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EigenMatrix::CopyFrom(const EigenMatrix& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EigenMatrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EigenMatrix::IsInitialized() const {
  return true;
}

void EigenMatrix::InternalSwap(EigenMatrix* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EigenMatrix, cols_)
      + sizeof(EigenMatrix::cols_)
      - PROTOBUF_FIELD_OFFSET(EigenMatrix, rows_)>(
          reinterpret_cast<char*>(&rows_),
          reinterpret_cast<char*>(&other->rows_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EigenMatrix::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class EigenVector::_Internal {
 public:
};

EigenVector::EigenVector(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  data_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:EigenVector)
}
EigenVector::EigenVector(const EigenVector& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_(from.data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  size_ = from.size_;
  // @@protoc_insertion_point(copy_constructor:EigenVector)
}

void EigenVector::SharedCtor() {
  size_ = 0u;
}

EigenVector::~EigenVector() {
  // @@protoc_insertion_point(destructor:EigenVector)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void EigenVector::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void EigenVector::ArenaDtor(void* object) {
  EigenVector* _this = reinterpret_cast< EigenVector* >(object);
  (void)_this;
}
void EigenVector::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void EigenVector::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EigenVector& EigenVector::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_EigenVector_state_2eproto.base);
  return *internal_default_instance();
}


void EigenVector::Clear() {
// @@protoc_insertion_point(message_clear_start:EigenVector)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  size_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EigenVector::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* EigenVector::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:EigenVector)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 size = 1;
  if (this->size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_size(), target);
  }

  // repeated double data = 2;
  if (this->_internal_data_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EigenVector)
  return target;
}

size_t EigenVector::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EigenVector)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double data = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // uint32 size = 1;
  if (this->size() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_size());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EigenVector::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EigenVector)
  GOOGLE_DCHECK_NE(&from, this);
  const EigenVector* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<EigenVector>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EigenVector)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EigenVector)
    MergeFrom(*source);
  }
}

void EigenVector::MergeFrom(const EigenVector& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EigenVector)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (from.size() != 0) {
    _internal_set_size(from._internal_size());
  }
}

void EigenVector::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EigenVector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EigenVector::CopyFrom(const EigenVector& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EigenVector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EigenVector::IsInitialized() const {
  return true;
}

void EigenVector::InternalSwap(EigenVector* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
  swap(size_, other->size_);
}

::PROTOBUF_NAMESPACE_ID::Metadata EigenVector::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class LambdaBlock::_Internal {
 public:
  static const ::EigenMatrix& phi(const LambdaBlock* msg);
  static const ::EigenMatrix& psi(const LambdaBlock* msg);
  static const ::EigenMatrix& lambda(const LambdaBlock* msg);
};

const ::EigenMatrix&
LambdaBlock::_Internal::phi(const LambdaBlock* msg) {
  return *msg->phi_;
}
const ::EigenMatrix&
LambdaBlock::_Internal::psi(const LambdaBlock* msg) {
  return *msg->psi_;
}
const ::EigenMatrix&
LambdaBlock::_Internal::lambda(const LambdaBlock* msg) {
  return *msg->lambda_;
}
LambdaBlock::LambdaBlock(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:LambdaBlock)
}
LambdaBlock::LambdaBlock(const LambdaBlock& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_phi()) {
    phi_ = new ::EigenMatrix(*from.phi_);
  } else {
    phi_ = nullptr;
  }
  if (from._internal_has_psi()) {
    psi_ = new ::EigenMatrix(*from.psi_);
  } else {
    psi_ = nullptr;
  }
  if (from._internal_has_lambda()) {
    lambda_ = new ::EigenMatrix(*from.lambda_);
  } else {
    lambda_ = nullptr;
  }
  tau_ = from.tau_;
  // @@protoc_insertion_point(copy_constructor:LambdaBlock)
}

void LambdaBlock::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LambdaBlock_state_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&phi_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&tau_) -
      reinterpret_cast<char*>(&phi_)) + sizeof(tau_));
}

LambdaBlock::~LambdaBlock() {
  // @@protoc_insertion_point(destructor:LambdaBlock)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LambdaBlock::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete phi_;
  if (this != internal_default_instance()) delete psi_;
  if (this != internal_default_instance()) delete lambda_;
}

void LambdaBlock::ArenaDtor(void* object) {
  LambdaBlock* _this = reinterpret_cast< LambdaBlock* >(object);
  (void)_this;
}
void LambdaBlock::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LambdaBlock::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LambdaBlock& LambdaBlock::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LambdaBlock_state_2eproto.base);
  return *internal_default_instance();
}


void LambdaBlock::Clear() {
// @@protoc_insertion_point(message_clear_start:LambdaBlock)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && phi_ != nullptr) {
    delete phi_;
  }
  phi_ = nullptr;
  if (GetArena() == nullptr && psi_ != nullptr) {
    delete psi_;
  }
  psi_ = nullptr;
  if (GetArena() == nullptr && lambda_ != nullptr) {
    delete lambda_;
  }
  lambda_ = nullptr;
  tau_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LambdaBlock::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // double tau = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          tau_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // .EigenMatrix phi = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_phi(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenMatrix psi = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_psi(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenMatrix lambda = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_lambda(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LambdaBlock::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LambdaBlock)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double tau = 1;
  if (!(this->tau() <= 0 && this->tau() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_tau(), target);
  }

  // .EigenMatrix phi = 2;
  if (this->has_phi()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::phi(this), target, stream);
  }

  // .EigenMatrix psi = 3;
  if (this->has_psi()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::psi(this), target, stream);
  }

  // .EigenMatrix lambda = 4;
  if (this->has_lambda()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::lambda(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LambdaBlock)
  return target;
}

size_t LambdaBlock::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LambdaBlock)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .EigenMatrix phi = 2;
  if (this->has_phi()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *phi_);
  }

  // .EigenMatrix psi = 3;
  if (this->has_psi()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *psi_);
  }

  // .EigenMatrix lambda = 4;
  if (this->has_lambda()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *lambda_);
  }

  // double tau = 1;
  if (!(this->tau() <= 0 && this->tau() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LambdaBlock::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LambdaBlock)
  GOOGLE_DCHECK_NE(&from, this);
  const LambdaBlock* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LambdaBlock>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LambdaBlock)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LambdaBlock)
    MergeFrom(*source);
  }
}

void LambdaBlock::MergeFrom(const LambdaBlock& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LambdaBlock)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_phi()) {
    _internal_mutable_phi()->::EigenMatrix::MergeFrom(from._internal_phi());
  }
  if (from.has_psi()) {
    _internal_mutable_psi()->::EigenMatrix::MergeFrom(from._internal_psi());
  }
  if (from.has_lambda()) {
    _internal_mutable_lambda()->::EigenMatrix::MergeFrom(from._internal_lambda());
  }
  if (!(from.tau() <= 0 && from.tau() >= 0)) {
    _internal_set_tau(from._internal_tau());
  }
}

void LambdaBlock::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LambdaBlock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LambdaBlock::CopyFrom(const LambdaBlock& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LambdaBlock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LambdaBlock::IsInitialized() const {
  return true;
}

void LambdaBlock::InternalSwap(LambdaBlock* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LambdaBlock, tau_)
      + sizeof(LambdaBlock::tau_)
      - PROTOBUF_FIELD_OFFSET(LambdaBlock, phi_)>(
          reinterpret_cast<char*>(&phi_),
          reinterpret_cast<char*>(&other->phi_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LambdaBlock::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class MultivariateMixtureState::_Internal {
 public:
  static const ::EigenVector& a_jumps(const MultivariateMixtureState* msg);
  static const ::EigenVector& na_jumps(const MultivariateMixtureState* msg);
  static const ::EigenVector& sigma_bar(const MultivariateMixtureState* msg);
  static const ::LambdaBlock& lamb_block(const MultivariateMixtureState* msg);
};

const ::EigenVector&
MultivariateMixtureState::_Internal::a_jumps(const MultivariateMixtureState* msg) {
  return *msg->a_jumps_;
}
const ::EigenVector&
MultivariateMixtureState::_Internal::na_jumps(const MultivariateMixtureState* msg) {
  return *msg->na_jumps_;
}
const ::EigenVector&
MultivariateMixtureState::_Internal::sigma_bar(const MultivariateMixtureState* msg) {
  return *msg->sigma_bar_;
}
const ::LambdaBlock&
MultivariateMixtureState::_Internal::lamb_block(const MultivariateMixtureState* msg) {
  return *msg->lamb_block_;
}
MultivariateMixtureState::MultivariateMixtureState(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  a_means_(arena),
  na_means_(arena),
  a_deltas_(arena),
  na_deltas_(arena),
  clus_alloc_(arena),
  etas_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MultivariateMixtureState)
}
MultivariateMixtureState::MultivariateMixtureState(const MultivariateMixtureState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      a_means_(from.a_means_),
      na_means_(from.na_means_),
      a_deltas_(from.a_deltas_),
      na_deltas_(from.na_deltas_),
      clus_alloc_(from.clus_alloc_),
      etas_(from.etas_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_a_jumps()) {
    a_jumps_ = new ::EigenVector(*from.a_jumps_);
  } else {
    a_jumps_ = nullptr;
  }
  if (from._internal_has_na_jumps()) {
    na_jumps_ = new ::EigenVector(*from.na_jumps_);
  } else {
    na_jumps_ = nullptr;
  }
  if (from._internal_has_sigma_bar()) {
    sigma_bar_ = new ::EigenVector(*from.sigma_bar_);
  } else {
    sigma_bar_ = nullptr;
  }
  if (from._internal_has_lamb_block()) {
    lamb_block_ = new ::LambdaBlock(*from.lamb_block_);
  } else {
    lamb_block_ = nullptr;
  }
  ::memcpy(&ma_, &from.ma_,
    static_cast<size_t>(reinterpret_cast<char*>(&mtot_) -
    reinterpret_cast<char*>(&ma_)) + sizeof(mtot_));
  // @@protoc_insertion_point(copy_constructor:MultivariateMixtureState)
}

void MultivariateMixtureState::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MultivariateMixtureState_state_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&a_jumps_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&mtot_) -
      reinterpret_cast<char*>(&a_jumps_)) + sizeof(mtot_));
}

MultivariateMixtureState::~MultivariateMixtureState() {
  // @@protoc_insertion_point(destructor:MultivariateMixtureState)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MultivariateMixtureState::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete a_jumps_;
  if (this != internal_default_instance()) delete na_jumps_;
  if (this != internal_default_instance()) delete sigma_bar_;
  if (this != internal_default_instance()) delete lamb_block_;
}

void MultivariateMixtureState::ArenaDtor(void* object) {
  MultivariateMixtureState* _this = reinterpret_cast< MultivariateMixtureState* >(object);
  (void)_this;
}
void MultivariateMixtureState::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MultivariateMixtureState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MultivariateMixtureState& MultivariateMixtureState::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MultivariateMixtureState_state_2eproto.base);
  return *internal_default_instance();
}


void MultivariateMixtureState::Clear() {
// @@protoc_insertion_point(message_clear_start:MultivariateMixtureState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  a_means_.Clear();
  na_means_.Clear();
  a_deltas_.Clear();
  na_deltas_.Clear();
  clus_alloc_.Clear();
  etas_.Clear();
  if (GetArena() == nullptr && a_jumps_ != nullptr) {
    delete a_jumps_;
  }
  a_jumps_ = nullptr;
  if (GetArena() == nullptr && na_jumps_ != nullptr) {
    delete na_jumps_;
  }
  na_jumps_ = nullptr;
  if (GetArena() == nullptr && sigma_bar_ != nullptr) {
    delete sigma_bar_;
  }
  sigma_bar_ = nullptr;
  if (GetArena() == nullptr && lamb_block_ != nullptr) {
    delete lamb_block_;
  }
  lamb_block_ = nullptr;
  ::memset(&ma_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mtot_) -
      reinterpret_cast<char*>(&ma_)) + sizeof(mtot_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MultivariateMixtureState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 ma = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 mna = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          mna_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 mtot = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          mtot_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .EigenVector a_means = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_a_means(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .EigenVector na_means = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_na_means(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .EigenMatrix a_deltas = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_a_deltas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .EigenMatrix na_deltas = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_na_deltas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      // .EigenVector a_jumps = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_a_jumps(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector na_jumps = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_na_jumps(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated int32 clus_alloc = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_clus_alloc(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80) {
          _internal_add_clus_alloc(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double u = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 89)) {
          u_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated .EigenVector etas = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_etas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<98>(ptr));
        } else goto handle_unusual;
        continue;
      // .EigenVector sigma_bar = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_sigma_bar(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .LambdaBlock lamb_block = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ctx->ParseMessage(_internal_mutable_lamb_block(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MultivariateMixtureState::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MultivariateMixtureState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ma = 1;
  if (this->ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_ma(), target);
  }

  // int32 mna = 2;
  if (this->mna() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_mna(), target);
  }

  // int32 mtot = 3;
  if (this->mtot() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_mtot(), target);
  }

  // repeated .EigenVector a_means = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_a_means_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_a_means(i), target, stream);
  }

  // repeated .EigenVector na_means = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_na_means_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_na_means(i), target, stream);
  }

  // repeated .EigenMatrix a_deltas = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_a_deltas_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_a_deltas(i), target, stream);
  }

  // repeated .EigenMatrix na_deltas = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_na_deltas_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, this->_internal_na_deltas(i), target, stream);
  }

  // .EigenVector a_jumps = 8;
  if (this->has_a_jumps()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::a_jumps(this), target, stream);
  }

  // .EigenVector na_jumps = 9;
  if (this->has_na_jumps()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        9, _Internal::na_jumps(this), target, stream);
  }

  // repeated int32 clus_alloc = 10;
  {
    int byte_size = _clus_alloc_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          10, _internal_clus_alloc(), byte_size, target);
    }
  }

  // double u = 11;
  if (!(this->u() <= 0 && this->u() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(11, this->_internal_u(), target);
  }

  // repeated .EigenVector etas = 12;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_etas_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, this->_internal_etas(i), target, stream);
  }

  // .EigenVector sigma_bar = 13;
  if (this->has_sigma_bar()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        13, _Internal::sigma_bar(this), target, stream);
  }

  // .LambdaBlock lamb_block = 14;
  if (this->has_lamb_block()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        14, _Internal::lamb_block(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MultivariateMixtureState)
  return target;
}

size_t MultivariateMixtureState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MultivariateMixtureState)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .EigenVector a_means = 4;
  total_size += 1UL * this->_internal_a_means_size();
  for (const auto& msg : this->a_means_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .EigenVector na_means = 5;
  total_size += 1UL * this->_internal_na_means_size();
  for (const auto& msg : this->na_means_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .EigenMatrix a_deltas = 6;
  total_size += 1UL * this->_internal_a_deltas_size();
  for (const auto& msg : this->a_deltas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .EigenMatrix na_deltas = 7;
  total_size += 1UL * this->_internal_na_deltas_size();
  for (const auto& msg : this->na_deltas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated int32 clus_alloc = 10;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->clus_alloc_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _clus_alloc_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .EigenVector etas = 12;
  total_size += 1UL * this->_internal_etas_size();
  for (const auto& msg : this->etas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .EigenVector a_jumps = 8;
  if (this->has_a_jumps()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *a_jumps_);
  }

  // .EigenVector na_jumps = 9;
  if (this->has_na_jumps()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *na_jumps_);
  }

  // .EigenVector sigma_bar = 13;
  if (this->has_sigma_bar()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *sigma_bar_);
  }

  // .LambdaBlock lamb_block = 14;
  if (this->has_lamb_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *lamb_block_);
  }

  // int32 ma = 1;
  if (this->ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_ma());
  }

  // int32 mna = 2;
  if (this->mna() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_mna());
  }

  // double u = 11;
  if (!(this->u() <= 0 && this->u() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 mtot = 3;
  if (this->mtot() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_mtot());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MultivariateMixtureState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MultivariateMixtureState)
  GOOGLE_DCHECK_NE(&from, this);
  const MultivariateMixtureState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MultivariateMixtureState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MultivariateMixtureState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MultivariateMixtureState)
    MergeFrom(*source);
  }
}

void MultivariateMixtureState::MergeFrom(const MultivariateMixtureState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MultivariateMixtureState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  a_means_.MergeFrom(from.a_means_);
  na_means_.MergeFrom(from.na_means_);
  a_deltas_.MergeFrom(from.a_deltas_);
  na_deltas_.MergeFrom(from.na_deltas_);
  clus_alloc_.MergeFrom(from.clus_alloc_);
  etas_.MergeFrom(from.etas_);
  if (from.has_a_jumps()) {
    _internal_mutable_a_jumps()->::EigenVector::MergeFrom(from._internal_a_jumps());
  }
  if (from.has_na_jumps()) {
    _internal_mutable_na_jumps()->::EigenVector::MergeFrom(from._internal_na_jumps());
  }
  if (from.has_sigma_bar()) {
    _internal_mutable_sigma_bar()->::EigenVector::MergeFrom(from._internal_sigma_bar());
  }
  if (from.has_lamb_block()) {
    _internal_mutable_lamb_block()->::LambdaBlock::MergeFrom(from._internal_lamb_block());
  }
  if (from.ma() != 0) {
    _internal_set_ma(from._internal_ma());
  }
  if (from.mna() != 0) {
    _internal_set_mna(from._internal_mna());
  }
  if (!(from.u() <= 0 && from.u() >= 0)) {
    _internal_set_u(from._internal_u());
  }
  if (from.mtot() != 0) {
    _internal_set_mtot(from._internal_mtot());
  }
}

void MultivariateMixtureState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MultivariateMixtureState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MultivariateMixtureState::CopyFrom(const MultivariateMixtureState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MultivariateMixtureState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MultivariateMixtureState::IsInitialized() const {
  return true;
}

void MultivariateMixtureState::InternalSwap(MultivariateMixtureState* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  a_means_.InternalSwap(&other->a_means_);
  na_means_.InternalSwap(&other->na_means_);
  a_deltas_.InternalSwap(&other->a_deltas_);
  na_deltas_.InternalSwap(&other->na_deltas_);
  clus_alloc_.InternalSwap(&other->clus_alloc_);
  etas_.InternalSwap(&other->etas_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MultivariateMixtureState, mtot_)
      + sizeof(MultivariateMixtureState::mtot_)
      - PROTOBUF_FIELD_OFFSET(MultivariateMixtureState, a_jumps_)>(
          reinterpret_cast<char*>(&a_jumps_),
          reinterpret_cast<char*>(&other->a_jumps_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MultivariateMixtureState::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class UnivariateMixtureState::_Internal {
 public:
  static const ::EigenVector& a_means(const UnivariateMixtureState* msg);
  static const ::EigenVector& na_means(const UnivariateMixtureState* msg);
  static const ::EigenVector& a_deltas(const UnivariateMixtureState* msg);
  static const ::EigenVector& na_deltas(const UnivariateMixtureState* msg);
  static const ::EigenVector& a_jumps(const UnivariateMixtureState* msg);
  static const ::EigenVector& na_jumps(const UnivariateMixtureState* msg);
  static const ::EigenVector& etas(const UnivariateMixtureState* msg);
  static const ::EigenVector& sigma_bar(const UnivariateMixtureState* msg);
  static const ::LambdaBlock& lamb_block(const UnivariateMixtureState* msg);
};

const ::EigenVector&
UnivariateMixtureState::_Internal::a_means(const UnivariateMixtureState* msg) {
  return *msg->a_means_;
}
const ::EigenVector&
UnivariateMixtureState::_Internal::na_means(const UnivariateMixtureState* msg) {
  return *msg->na_means_;
}
const ::EigenVector&
UnivariateMixtureState::_Internal::a_deltas(const UnivariateMixtureState* msg) {
  return *msg->a_deltas_;
}
const ::EigenVector&
UnivariateMixtureState::_Internal::na_deltas(const UnivariateMixtureState* msg) {
  return *msg->na_deltas_;
}
const ::EigenVector&
UnivariateMixtureState::_Internal::a_jumps(const UnivariateMixtureState* msg) {
  return *msg->a_jumps_;
}
const ::EigenVector&
UnivariateMixtureState::_Internal::na_jumps(const UnivariateMixtureState* msg) {
  return *msg->na_jumps_;
}
const ::EigenVector&
UnivariateMixtureState::_Internal::etas(const UnivariateMixtureState* msg) {
  return *msg->etas_;
}
const ::EigenVector&
UnivariateMixtureState::_Internal::sigma_bar(const UnivariateMixtureState* msg) {
  return *msg->sigma_bar_;
}
const ::LambdaBlock&
UnivariateMixtureState::_Internal::lamb_block(const UnivariateMixtureState* msg) {
  return *msg->lamb_block_;
}
UnivariateMixtureState::UnivariateMixtureState(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  clus_alloc_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:UnivariateMixtureState)
}
UnivariateMixtureState::UnivariateMixtureState(const UnivariateMixtureState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      clus_alloc_(from.clus_alloc_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_a_means()) {
    a_means_ = new ::EigenVector(*from.a_means_);
  } else {
    a_means_ = nullptr;
  }
  if (from._internal_has_na_means()) {
    na_means_ = new ::EigenVector(*from.na_means_);
  } else {
    na_means_ = nullptr;
  }
  if (from._internal_has_a_deltas()) {
    a_deltas_ = new ::EigenVector(*from.a_deltas_);
  } else {
    a_deltas_ = nullptr;
  }
  if (from._internal_has_na_deltas()) {
    na_deltas_ = new ::EigenVector(*from.na_deltas_);
  } else {
    na_deltas_ = nullptr;
  }
  if (from._internal_has_a_jumps()) {
    a_jumps_ = new ::EigenVector(*from.a_jumps_);
  } else {
    a_jumps_ = nullptr;
  }
  if (from._internal_has_na_jumps()) {
    na_jumps_ = new ::EigenVector(*from.na_jumps_);
  } else {
    na_jumps_ = nullptr;
  }
  if (from._internal_has_etas()) {
    etas_ = new ::EigenVector(*from.etas_);
  } else {
    etas_ = nullptr;
  }
  if (from._internal_has_sigma_bar()) {
    sigma_bar_ = new ::EigenVector(*from.sigma_bar_);
  } else {
    sigma_bar_ = nullptr;
  }
  if (from._internal_has_lamb_block()) {
    lamb_block_ = new ::LambdaBlock(*from.lamb_block_);
  } else {
    lamb_block_ = nullptr;
  }
  ::memcpy(&ma_, &from.ma_,
    static_cast<size_t>(reinterpret_cast<char*>(&mtot_) -
    reinterpret_cast<char*>(&ma_)) + sizeof(mtot_));
  // @@protoc_insertion_point(copy_constructor:UnivariateMixtureState)
}

void UnivariateMixtureState::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_UnivariateMixtureState_state_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&a_means_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&mtot_) -
      reinterpret_cast<char*>(&a_means_)) + sizeof(mtot_));
}

UnivariateMixtureState::~UnivariateMixtureState() {
  // @@protoc_insertion_point(destructor:UnivariateMixtureState)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void UnivariateMixtureState::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete a_means_;
  if (this != internal_default_instance()) delete na_means_;
  if (this != internal_default_instance()) delete a_deltas_;
  if (this != internal_default_instance()) delete na_deltas_;
  if (this != internal_default_instance()) delete a_jumps_;
  if (this != internal_default_instance()) delete na_jumps_;
  if (this != internal_default_instance()) delete etas_;
  if (this != internal_default_instance()) delete sigma_bar_;
  if (this != internal_default_instance()) delete lamb_block_;
}

void UnivariateMixtureState::ArenaDtor(void* object) {
  UnivariateMixtureState* _this = reinterpret_cast< UnivariateMixtureState* >(object);
  (void)_this;
}
void UnivariateMixtureState::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void UnivariateMixtureState::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const UnivariateMixtureState& UnivariateMixtureState::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_UnivariateMixtureState_state_2eproto.base);
  return *internal_default_instance();
}


void UnivariateMixtureState::Clear() {
// @@protoc_insertion_point(message_clear_start:UnivariateMixtureState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clus_alloc_.Clear();
  if (GetArena() == nullptr && a_means_ != nullptr) {
    delete a_means_;
  }
  a_means_ = nullptr;
  if (GetArena() == nullptr && na_means_ != nullptr) {
    delete na_means_;
  }
  na_means_ = nullptr;
  if (GetArena() == nullptr && a_deltas_ != nullptr) {
    delete a_deltas_;
  }
  a_deltas_ = nullptr;
  if (GetArena() == nullptr && na_deltas_ != nullptr) {
    delete na_deltas_;
  }
  na_deltas_ = nullptr;
  if (GetArena() == nullptr && a_jumps_ != nullptr) {
    delete a_jumps_;
  }
  a_jumps_ = nullptr;
  if (GetArena() == nullptr && na_jumps_ != nullptr) {
    delete na_jumps_;
  }
  na_jumps_ = nullptr;
  if (GetArena() == nullptr && etas_ != nullptr) {
    delete etas_;
  }
  etas_ = nullptr;
  if (GetArena() == nullptr && sigma_bar_ != nullptr) {
    delete sigma_bar_;
  }
  sigma_bar_ = nullptr;
  if (GetArena() == nullptr && lamb_block_ != nullptr) {
    delete lamb_block_;
  }
  lamb_block_ = nullptr;
  ::memset(&ma_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mtot_) -
      reinterpret_cast<char*>(&ma_)) + sizeof(mtot_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnivariateMixtureState::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 ma = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ma_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 mna = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          mna_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 mtot = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          mtot_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector a_means = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_a_means(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector na_means = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_na_means(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector a_deltas = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_a_deltas(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector na_deltas = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_na_deltas(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector a_jumps = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_a_jumps(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector na_jumps = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_na_jumps(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated int32 clus_alloc = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_clus_alloc(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80) {
          _internal_add_clus_alloc(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // double u = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 89)) {
          u_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // .EigenVector etas = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_etas(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .EigenVector sigma_bar = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_sigma_bar(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .LambdaBlock lamb_block = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ctx->ParseMessage(_internal_mutable_lamb_block(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* UnivariateMixtureState::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:UnivariateMixtureState)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ma = 1;
  if (this->ma() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_ma(), target);
  }

  // int32 mna = 2;
  if (this->mna() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_mna(), target);
  }

  // int32 mtot = 3;
  if (this->mtot() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_mtot(), target);
  }

  // .EigenVector a_means = 4;
  if (this->has_a_means()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::a_means(this), target, stream);
  }

  // .EigenVector na_means = 5;
  if (this->has_na_means()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::na_means(this), target, stream);
  }

  // .EigenVector a_deltas = 6;
  if (this->has_a_deltas()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::a_deltas(this), target, stream);
  }

  // .EigenVector na_deltas = 7;
  if (this->has_na_deltas()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::na_deltas(this), target, stream);
  }

  // .EigenVector a_jumps = 8;
  if (this->has_a_jumps()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::a_jumps(this), target, stream);
  }

  // .EigenVector na_jumps = 9;
  if (this->has_na_jumps()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        9, _Internal::na_jumps(this), target, stream);
  }

  // repeated int32 clus_alloc = 10;
  {
    int byte_size = _clus_alloc_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          10, _internal_clus_alloc(), byte_size, target);
    }
  }

  // double u = 11;
  if (!(this->u() <= 0 && this->u() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(11, this->_internal_u(), target);
  }

  // .EigenVector etas = 12;
  if (this->has_etas()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        12, _Internal::etas(this), target, stream);
  }

  // .EigenVector sigma_bar = 13;
  if (this->has_sigma_bar()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        13, _Internal::sigma_bar(this), target, stream);
  }

  // .LambdaBlock lamb_block = 14;
  if (this->has_lamb_block()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        14, _Internal::lamb_block(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:UnivariateMixtureState)
  return target;
}

size_t UnivariateMixtureState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:UnivariateMixtureState)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 clus_alloc = 10;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->clus_alloc_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _clus_alloc_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .EigenVector a_means = 4;
  if (this->has_a_means()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *a_means_);
  }

  // .EigenVector na_means = 5;
  if (this->has_na_means()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *na_means_);
  }

  // .EigenVector a_deltas = 6;
  if (this->has_a_deltas()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *a_deltas_);
  }

  // .EigenVector na_deltas = 7;
  if (this->has_na_deltas()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *na_deltas_);
  }

  // .EigenVector a_jumps = 8;
  if (this->has_a_jumps()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *a_jumps_);
  }

  // .EigenVector na_jumps = 9;
  if (this->has_na_jumps()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *na_jumps_);
  }

  // .EigenVector etas = 12;
  if (this->has_etas()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *etas_);
  }

  // .EigenVector sigma_bar = 13;
  if (this->has_sigma_bar()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *sigma_bar_);
  }

  // .LambdaBlock lamb_block = 14;
  if (this->has_lamb_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *lamb_block_);
  }

  // int32 ma = 1;
  if (this->ma() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_ma());
  }

  // int32 mna = 2;
  if (this->mna() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_mna());
  }

  // double u = 11;
  if (!(this->u() <= 0 && this->u() >= 0)) {
    total_size += 1 + 8;
  }

  // int32 mtot = 3;
  if (this->mtot() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_mtot());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UnivariateMixtureState::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:UnivariateMixtureState)
  GOOGLE_DCHECK_NE(&from, this);
  const UnivariateMixtureState* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<UnivariateMixtureState>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:UnivariateMixtureState)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:UnivariateMixtureState)
    MergeFrom(*source);
  }
}

void UnivariateMixtureState::MergeFrom(const UnivariateMixtureState& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:UnivariateMixtureState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  clus_alloc_.MergeFrom(from.clus_alloc_);
  if (from.has_a_means()) {
    _internal_mutable_a_means()->::EigenVector::MergeFrom(from._internal_a_means());
  }
  if (from.has_na_means()) {
    _internal_mutable_na_means()->::EigenVector::MergeFrom(from._internal_na_means());
  }
  if (from.has_a_deltas()) {
    _internal_mutable_a_deltas()->::EigenVector::MergeFrom(from._internal_a_deltas());
  }
  if (from.has_na_deltas()) {
    _internal_mutable_na_deltas()->::EigenVector::MergeFrom(from._internal_na_deltas());
  }
  if (from.has_a_jumps()) {
    _internal_mutable_a_jumps()->::EigenVector::MergeFrom(from._internal_a_jumps());
  }
  if (from.has_na_jumps()) {
    _internal_mutable_na_jumps()->::EigenVector::MergeFrom(from._internal_na_jumps());
  }
  if (from.has_etas()) {
    _internal_mutable_etas()->::EigenVector::MergeFrom(from._internal_etas());
  }
  if (from.has_sigma_bar()) {
    _internal_mutable_sigma_bar()->::EigenVector::MergeFrom(from._internal_sigma_bar());
  }
  if (from.has_lamb_block()) {
    _internal_mutable_lamb_block()->::LambdaBlock::MergeFrom(from._internal_lamb_block());
  }
  if (from.ma() != 0) {
    _internal_set_ma(from._internal_ma());
  }
  if (from.mna() != 0) {
    _internal_set_mna(from._internal_mna());
  }
  if (!(from.u() <= 0 && from.u() >= 0)) {
    _internal_set_u(from._internal_u());
  }
  if (from.mtot() != 0) {
    _internal_set_mtot(from._internal_mtot());
  }
}

void UnivariateMixtureState::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:UnivariateMixtureState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnivariateMixtureState::CopyFrom(const UnivariateMixtureState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UnivariateMixtureState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnivariateMixtureState::IsInitialized() const {
  return true;
}

void UnivariateMixtureState::InternalSwap(UnivariateMixtureState* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  clus_alloc_.InternalSwap(&other->clus_alloc_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UnivariateMixtureState, mtot_)
      + sizeof(UnivariateMixtureState::mtot_)
      - PROTOBUF_FIELD_OFFSET(UnivariateMixtureState, a_means_)>(
          reinterpret_cast<char*>(&a_means_),
          reinterpret_cast<char*>(&other->a_means_));
}

::PROTOBUF_NAMESPACE_ID::Metadata UnivariateMixtureState::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::EigenMatrix* Arena::CreateMaybeMessage< ::EigenMatrix >(Arena* arena) {
  return Arena::CreateMessageInternal< ::EigenMatrix >(arena);
}
template<> PROTOBUF_NOINLINE ::EigenVector* Arena::CreateMaybeMessage< ::EigenVector >(Arena* arena) {
  return Arena::CreateMessageInternal< ::EigenVector >(arena);
}
template<> PROTOBUF_NOINLINE ::LambdaBlock* Arena::CreateMaybeMessage< ::LambdaBlock >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LambdaBlock >(arena);
}
template<> PROTOBUF_NOINLINE ::MultivariateMixtureState* Arena::CreateMaybeMessage< ::MultivariateMixtureState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MultivariateMixtureState >(arena);
}
template<> PROTOBUF_NOINLINE ::UnivariateMixtureState* Arena::CreateMaybeMessage< ::UnivariateMixtureState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::UnivariateMixtureState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
